### ISSUE TITLE
[JFContraFome] Alterar CRUD de benefício - 5h

### ISSUE THREAD

**Issue by jfbaraky** [app-masters/e-beneficio#259]
- Depende da variável criada na issue #256;

- [x] Quando o TYPE for `ticket` o benefício terá o valor em dinheiro;
- [x] Quando o TYPE for `product` o usuário terá que escolher na lista de produtos quais os produtos e quantidades de cada um para vincular no benefício;
- [x] Enviar array de produtos na chave `products` com os valores no formato:
```
[{ productId: 1, amount: 2}, {productId: 2, amount: 3}]
```
- [x] Esse componente para selecionar a quantidade de produtos na view pode ser um pouco complicado, mas acho que o melhor jeito é listar todos os produtos (não serão muitos) e mostrar dois icones, um para subir o número outro para descer o número e ir mostrando a contagem do lado (enviar foto para discutirmos). Tentar fazer ele reaproveitável para utilizarmos em outros lugares;

![image](https://user-images.githubusercontent.com/20716607/83795580-0d6fbd80-a676-11ea-99f3-4f185e1d2547.png)

- [x] NÃO enviar para o backend se o amount for zero;

- [x] Após abrir o PR, comentar na ISSUE quanto tempo levou na issue;

**Comment by allanmaral** [comment]
Foram 4 horas e 29 minutos para fazer as alterações no crud e 2 horas e 12 minutos para adequar as alterações o crud ao que tinha sido feito no backend e realizar os fixes necessários no backend. Totalizando 6 horas e 41 minutos.
